title: Surager # 站点标题
description: | # 头像背后的信息（html格式），<br/>代表换行
  #头像下面的文字，<br/>
  可以替换成一句很有哲理的话。<br/>
  比如 “可以替换成一句很有哲理的话。” <br/>
url: https://surager.pub # 你的域名，例如 https://wu-kan.github.io
baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。

sass:
  sass_dir: _sass
  style: compressed

defaults: # 将所有配置选项使用<https://jekyllrb.com/docs/configuration/front-matter-defaults/>功能进行配置
  - scope:
      path: "" # an empty string here means all files in the project
    values: # 以下配置项也可以在任意页面自定义
      categories: "_posts"
      math: false
      mermaid: false
      prism: true
      jekyll-theme-WuK:
        default:
          body:
            theme-base: theme-base-07 # 可选的主题色包括08~0f，见 <https://github.com/poole/lanyon>
            layout-reverse: false # 开启后sidebar在右边，反之左边
            sidebar-overlay: true # 开启后正文不随sidebar移动而移动
        page:
          title:
            enable: false
          masthead:
            enable: false
          katex:
            enable: false
          mermaid:
            enable: false
          prism:
            enable: false
        post:
          date:
            enable: true
          wordcount:
            enable: false
            unit: 字
          readtime:
            enable: false
            unit: 分
            divided_by: 300 # 正常人的阅读速度大概每分钟三百个字
          tags:
            enable: true
          related_posts:
            enable: false
        tags:
          pie_chart:
            enable: false
          count: true
          toc:
            enable: false
        archive:
          group_by: "%Y" # 见<https://liquid.bootcss.com/filters/date/>
          posts_count:
            enable: true
            append: 篇博文。长路漫漫！ # 提示语
          pie_chart:
            enable: false
          year_count: true
          toc:
            enable: false
        home: # 展示页的配置可跳过，详见<https://revealjs.com/>
          append_to_section_tag:
            - key: data-markdown
            - key: data-separator # 水平展示页分隔符
              value: <!-- .slide -->
            - key: data-separator-vertical # 垂直展示页分隔符
              value: <!-- .slide vertical=true -->
            - key: data-background-color
              value: "White"

compress_html: # <https://github.com/penibelst/jekyll-compress-html>
  clippings: all
  comments: [] # 注释不能压缩，否则 reveal.js 的 ppt切屏受影响
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# githubpage上支持的插件见<https://pages.github.com/versions/>
plugins: # <https://jekyllrb.com/docs/plugins/>
  - jekyll-readme-index # 使用readme做index，从而和github渲染效果一致
  - jekyll-default-layout # 为每个markdown自动生成layout
  - jekyll-seo-tag # 为每个页面生成标题
  - jekyll-sitemap # 为站点生成站点地图
  - jekyll-feed # 为站点生成RSS源

#remote_theme: https://github.com/wu-kan/jekyll-theme-WuK@4.0.2 #使用固定版本号以防止主题更新导致站点显示错乱

readme_index: # 缺失index.md和index.html时，使用README.md代替之
  with_frontmatter: true # 支持带有yaml头的README

webmaster_verifications: # <https://jekyll.github.io/jekyll-seo-tag/usage/>
  google: YIKi1rBnyUaS-DMYiluseI5kZzTwjCkTFmKkSkMZDJk
  baidu: szbTSfUGAB

permalink: /:categories/:year-:month-:day-:title/ #生成文章的地址格式，我希望它和_posts目录下的格式一样
# timezone: Asia/Shanghai # 解决githubpage显示时间不正确的问题，见<https://www.iana.org/time-zones>
future: true # 允许发布时间在未来的文章

# limit_posts: 999 # 限制博文数量
# encoding: utf-8

markdown: kramdown
kramdown: # 见<https://kramdown.gettalong.org/options.html>
  input: GFM # 见<http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # 可见<https://kramdown.gettalong.org/options.html>
    block:
      disable: true # 关掉代码块默认的高亮，换用prismjs
      line_numbers: false #渲染出来的效果好鬼畜
    span:
      disable: true
# 以下为 githubpage上不可修改的参数，见<https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll>
#lsi: false # 为相关文章生成索引
#safe: true # 禁用自定义插件
#source: [your repo's top level directory] # Jekyll 读取文件的路径
#incremental: false # 增量生成
#highlighter: rouge # 代码高亮器
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
